server:
  port: 8080
  servlet:
    context-path: / #变更2
#  context-path: /
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    basedir: D:/data/tomcat8-application/${spring.application.name}/
    max-http-post-size: 10485760
    accesslog:
      enabled: true
      pattern: common
      directory: logs
#变更1
spring:
  security:
    user:
      name: admin
      password: admin123
      
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7100/eureka/

logging:
   appender: console
   path: /data/logs/
   pattern:
    level: info